name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  use-reusable-workflow:
    uses: projeto-devops-gabriela/esteiras-devops/.github/workflows/esteira-teste-conexao.yaml@main
    with:
       project-type: 'ClassLibrary'
       build-configuration: Release
    secrets: inherit